
replicaCount: 1

image:
  repository: nexus-repo-nexus-repository-manager:8082/repository/docker-repo/apostoliseq/test-app:1.0
  pullPolicy: Always
  tag: "1.0"

service:
  type: NodePort
  port: 8080
  nodePort: 32080